export const BR_OL_APP_OPENED = 'BR_OL_APP_OPENED'

// Auth
export const BR_OL_AUTHENTICATE_CLICKED = 'BR_OL_AUTHENTICATE_CLICKED'
export const BR_OL_AUTHENTICATE_SUCCESS = 'BR_OL_AUTHENTICATE_SUCCESS'
export const BR_OL_AUTHENTICATE_FAILURE = 'BR_OL_AUTHENTICATE_FAILURE'
export const BR_OL_LOGIN = 'BR_OL_LOGIN'
export const BR_OL_LOGIN_SUCCESS = 'BR_OL_LOGIN_SUCCESS'
export const BR_OL_LOGIN_FAILURE = 'BR_OL_LOGIN_FAILURE'

// CommandBar
export const BR_OL_ADD_CONTACT_COMMAND_BAR_CLICKED = 'BR_OL_ADD_CONTACT_COMMAND_BAR_CLICKED'
export const BR_OL_FILTER_CONTACTS_COMMAND_BAR_CLICKED = 'BR_OL_FILTER_CONTACTS_COMMAND_BAR_CLICKED'
export const BR_OL_SEARCH_CONTACTS_COMMAND_BAR_CLICKED = 'BR_OL_SEARCH_CONTACTS_COMMAND_BAR_CLICKED'

// Add contact
export const BR_OL_ADD_CONTACT_CLICKED = 'BR_OL_ADD_CONTACT_CLICKED'
export const BR_OL_ADD_CONTACT_SUCCESS = 'BR_OL_ADD_CONTACT_SUCCESS'
export const BR_OL_ADD_CONTACT_FAILURE = 'BR_OL_ADD_CONTACT_FAILURE'
export const BR_OL_ADD_CONTACT_AUTOFILL_CLICKED = 'BR_OL_ADD_CONTACT_AUTOFILL_CLICKED'

// Add reminder
export const BR_OL_ADD_REMINDER_CLICKED = 'BR_OL_ADD_REMINDER_CLICKED'
export const BR_OL_ADD_REMINDER_SUCCESS = 'BR_OL_ADD_REMINDER_SUCCESS'
export const BR_OL_ADD_REMINDER_FAILURE = 'BR_OL_ADD_REMINDER_FAILURE'
export const BR_OL_SKIP_REMINDER_CLICKED = 'BR_OL_SKIP_REMINDER_CLICKED'

// Filter contacts
export const BR_OL_FILTER_CONTACTS_CLICKED = 'BR_OL_FILTER_CONTACTS_CLICKED'
export const BR_OL_FILTER_CONTACTS_SUCCESS = 'BR_OL_FILTER_CONTACTS_SUCCESS'
export const BR_OL_FILTER_CONTACTS_FAILURE = 'BR_OL_FILTER_CONTACTS_FAILURE'

// Search contacts
export const BR_OL_SEARCH_CONTACTS_CLICKED = 'BR_OL_SEARCH_CONTACTS_CLICKED'

// View contact
export const BR_OL_VIEW_CONTACT = 'BR_OL_VIEW_CONTACT'
export const BR_OL_VIEW_CONTACT_OPEN_NOTES = 'BR_OL_VIEW_CONTACT_OPEN_NOTES'
export const BR_OL_VIEW_CONTACT_SAVE_NOTES_SUCCESS = 'BR_OL_VIEW_CONTACT_SAVE_NOTES_SUCCESS'
export const BR_OL_VIEW_CONTACT_SAVE_NOTES_FAILURE = 'BR_OL_VIEW_CONTACT_SAVE_NOTES_FAILURE'
